In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [5]:
# 데이터 불러오기
df_mid = pd.read_csv('data/서울시 중학교 기본정보.csv', encoding='cp949')
df_high = pd.read_csv('data/서울시 고등학교 기본정보.csv', encoding='cp949')
df_open = pd.read_csv('data/서울특별시교육청_민간개방 학교시설물현황_20250910.csv', encoding='cp949')

In [6]:
# 중복값 제거하기
df_mid.drop_duplicates(inplace=True)
df_high.drop_duplicates(inplace=True)

In [10]:
df_mid.head()

,학교종류명,설립구분,표준학교코드,학교명,영문학교명,관할조직명,도로명우편번호,도로명주소,도로명상세주소,전화번호,...,고등학교일반실업구분명,특수목적고등학교계열명,입시전후기구분명,주야구분명,설립일자,개교기념일,시도교육청코드,시도교육청명,소재지명,적재일시
0,중학교,사립,7134161,동국대학교사범대학부속가람중학교,Garam Middle School Attached to College of Edu...,서울특별시성동광진교육지원청,5038,서울특별시 광진구 광나루로36길 47,", 동국대학교사범대학부속가람중학교 (구의동)",02-6948-2280,...,일반계,NaN,전기,주간,19300620,19300620,B10,서울특별시교육청,서울특별시,20250302
2,중학교,공립,7134142,행당중학교,Haengdang Middle School,서울특별시성동광진교육지원청,4764,서울특별시 성동구 왕십리로 189,(행당동/행당중학교),02-2292-2721,...,일반계,NaN,전기,주간,19680806,19681002,B10,서울특별시교육청,서울특별시,20230615
4,중학교,사립,7134141,한양대학교사범대학부속중학교,Hanyang University Middle School,서울특별시성동광진교육지원청,4761,서울특별시 성동구 마조로 42,(사근동/한양사대부속중?고등학교),02-2200-3700,...,일반계,NaN,전기,주간,19600118,19600118,B10,서울특별시교육청,서울특별시,20230615
6,중학교,공립,7134140,자양중학교,Jayang Middle School,서울특별시성동광진교육지원청,5069,서울특별시 광진구 뚝섬로41길 33,(자양동/서울자양중학교),02-446-0365,...,일반계,NaN,전기,주간,19840301,19840301,B10,서울특별시교육청,서울특별시,20230615
8,중학교,공립,7134139,용곡중학교,Yong-gok Middle School,서울특별시성동광진교육지원청,4940,서울특별시 광진구 용마산로22길 76,(중곡동/용곡중학교),02-452-2622,...,일반계,NaN,전기,주간,19821209,19830504,B10,서울특별시교육청,서울특별시,20230615

In [12]:
df_high.head()

,학교종류명,설립구분,표준학교코드,학교명,영문학교명,관할조직명,도로명우편번호,도로명주소,도로명상세주소,전화번호,...,고등학교일반실업구분명,특수목적고등학교계열명,입시전후기구분명,주야구분명,설립일자,개교기념일,시도교육청코드,시도교육청명,소재지명,적재일시
0,고등학교,사립,7011651,서울홍신고등학교,seoul-hongshin High School,서울특별시교육청,7638,서울특별시 강서구 강서로45길 70,"(내발산동, 서울홍신고등학교)",070-8644-6300,...,전문계,NaN,전기,주간,19870108,19870916,B10,서울특별시교육청,서울특별시,20240414
2,고등학교,사립,7011650,한양과학기술고등학교,Hanyang Science And Technology High School,서울특별시교육청,4566,서울특별시 중구 을지로 299,(신당동),02-2238-5181,...,전문계,NaN,전기,주간,19450901,19450901,B10,서울특별시교육청,서울특별시,20260329
4,고등학교,공립,7011649,흑석고등학교,Heukseok High School,서울특별시교육청,6985,서울특별시 동작구 흑석한강로 36,(흑석동),02-399-9605,...,일반계,NaN,후기,주간,20260301,20260301,B10,서울특별시교육청,서울특별시,20260201
6,고등학교,사립,7011586,동국대학교사범대학부속가람고등학교,Garam High School Attached To College Of Educa...,서울특별시교육청,5038,서울특별시 광진구 광나루로36길 47,동국대학교사범대학부속가람고등학교,0220491577,...,일반계,NaN,후기,주간,19300620,19300620,B10,서울특별시교육청,서울특별시,20250302
8,고등학교,공립,7011585,서울디지털콘텐츠고등학교,Seoul Digital Content High School,서울특별시교육청,7514,서울특별시 강서구 방화대로47길 9,"(방화동,서울디지털콘텐츠고등학교)",02-2666-2106,...,전문계,NaN,전기,주간,19940105,19940105,B10,서울특별시교육청,서울특별시,20230615

In [8]:
# 중학교 개수 확인
num_mid = df_mid['학교명'].nunique()
print(f'서울시 중학교 개수: {num_mid}')

# 고등학교 개수 확인
num_high = df_high['학교명'].nunique()
print(f'서울시 고등학교 개수: {num_high}')

서울시 중학교 개수: 390
서울시 고등학교 개수: 319

In [13]:
df_open.head()

,시도교육청,교육지원청,지역,학교명,학교급코드,교실 개방여부,시청각실 개방여부,체육관 개방여부,운동장 개방여부,수영장 개방여부,테니스장 개방여부,잔디운동장 개방여부
0,서울특별시교육청,서울특별시교육청,송파구,가락고등학교,고,무,시설없음,무,시설없음,시설없음,시설없음,시설없음
1,서울특별시교육청,서울특별시강동송파교육지원청,송파구,가락중학교,중,유,시설없음,무,유,시설없음,시설없음,시설없음
2,서울특별시교육청,서울특별시남부교육지원청,금천구,가산중학교,중,무,시설없음,유,시설없음,시설없음,시설없음,유
3,서울특별시교육청,서울특별시강동송파교육지원청,송파구,가원중학교,중,유,시설없음,시설없음,시설없음,시설없음,시설없음,시설없음
4,서울특별시교육청,서울특별시교육청,서대문구,가재울고등학교,고,무,시설없음,시설없음,유,시설없음,시설없음,시설없음

In [9]:
# 중학교 중 공립/사립 개수 확인
mid_public = df_mid[df_mid['설립구분'] == '공립']['학교명'].nunique()
mid_private = df_mid[df_mid['설립구분'] == '사립']['학교명'].nunique()
print(f'서울시 중학교 공립 개수: {mid_public}')
print(f'서울시 중학교 사립 개수: {mid_private}')
# 고등학교 중 공립/사립 개수 확인
high_public = df_high[df_high['설립구분'] == '공립']['학교명'].nunique()
high_private = df_high[df_high['설립구분'] == '사립']['학교명'].nunique()
print(f'서울시 고등학교 공립 개수: {high_public}')
print(f'서울시 고등학교 사립 개수: {high_private}')

서울시 중학교 공립 개수: 279
서울시 중학교 사립 개수: 109
서울시 고등학교 공립 개수: 116
서울시 고등학교 사립 개수: 200

In [11]:
# 데이터 합치기
df_combined = pd.concat([df_mid, df_high], ignore_index=True)
df_combined.head()

,학교종류명,설립구분,표준학교코드,학교명,영문학교명,관할조직명,도로명우편번호,도로명주소,도로명상세주소,전화번호,...,고등학교일반실업구분명,특수목적고등학교계열명,입시전후기구분명,주야구분명,설립일자,개교기념일,시도교육청코드,시도교육청명,소재지명,적재일시
0,중학교,사립,7134161,동국대학교사범대학부속가람중학교,Garam Middle School Attached to College of Edu...,서울특별시성동광진교육지원청,5038,서울특별시 광진구 광나루로36길 47,", 동국대학교사범대학부속가람중학교 (구의동)",02-6948-2280,...,일반계,NaN,전기,주간,19300620,19300620,B10,서울특별시교육청,서울특별시,20250302
1,중학교,공립,7134142,행당중학교,Haengdang Middle School,서울특별시성동광진교육지원청,4764,서울특별시 성동구 왕십리로 189,(행당동/행당중학교),02-2292-2721,...,일반계,NaN,전기,주간,19680806,19681002,B10,서울특별시교육청,서울특별시,20230615
2,중학교,사립,7134141,한양대학교사범대학부속중학교,Hanyang University Middle School,서울특별시성동광진교육지원청,4761,서울특별시 성동구 마조로 42,(사근동/한양사대부속중?고등학교),02-2200-3700,...,일반계,NaN,전기,주간,19600118,19600118,B10,서울특별시교육청,서울특별시,20230615
3,중학교,공립,7134140,자양중학교,Jayang Middle School,서울특별시성동광진교육지원청,5069,서울특별시 광진구 뚝섬로41길 33,(자양동/서울자양중학교),02-446-0365,...,일반계,NaN,전기,주간,19840301,19840301,B10,서울특별시교육청,서울특별시,20230615
4,중학교,공립,7134139,용곡중학교,Yong-gok Middle School,서울특별시성동광진교육지원청,4940,서울특별시 광진구 용마산로22길 76,(중곡동/용곡중학교),02-452-2622,...,일반계,NaN,전기,주간,19821209,19830504,B10,서울특별시교육청,서울특별시,20230615

In [14]:
# 민간개방 데이터의 '금호여자중학교'를 '금호중학교'로 변경
df_open['학교명'] = df_open['학교명'].replace('금호여자중학교', '금호중학교')

# 민간개방 데이터와 합쳐진 데이터에서 학교명 기준으로 일치하는 학교 개수 확인
open_schools = df_open['학교명'].unique()
combined_schools = df_combined['학교명'].unique()
matching_schools = set(open_schools) & set(combined_schools)
print(f'민간개방 데이터와 합쳐진 데이터에서 일치하는 학교 개수: {len(matching_schools)}')

민간개방 데이터와 합쳐진 데이터에서 일치하는 학교 개수: 394

In [15]:
# 민간개방 데이터와 합쳐진 데이터를 합치기
df_final = pd.merge(df_combined, df_open, on='학교명', how='inner')
df_final.head()

,학교종류명,설립구분,표준학교코드,학교명,영문학교명,관할조직명,도로명우편번호,도로명주소,도로명상세주소,전화번호,...,교육지원청,지역,학교급코드,교실 개방여부,시청각실 개방여부,체육관 개방여부,운동장 개방여부,수영장 개방여부,테니스장 개방여부,잔디운동장 개방여부
0,중학교,공립,7134142,행당중학교,Haengdang Middle School,서울특별시성동광진교육지원청,4764,서울특별시 성동구 왕십리로 189,(행당동/행당중학교),02-2292-2721,...,서울특별시성동광진교육지원청,성동구,중,유,시설없음,무,유,시설없음,시설없음,시설없음
1,중학교,공립,7134140,자양중학교,Jayang Middle School,서울특별시성동광진교육지원청,5069,서울특별시 광진구 뚝섬로41길 33,(자양동/서울자양중학교),02-446-0365,...,서울특별시성동광진교육지원청,광진구,중,무,시설없음,무,시설없음,시설없음,시설없음,무
2,중학교,공립,7134139,용곡중학교,Yong-gok Middle School,서울특별시성동광진교육지원청,4940,서울특별시 광진구 용마산로22길 76,(중곡동/용곡중학교),02-452-2622,...,서울특별시성동광진교육지원청,광진구,중,무,무,무,시설없음,시설없음,시설없음,유
3,중학교,공립,7134138,옥정중학교,Ok-Jung Middle School,서울특별시성동광진교육지원청,4734,서울특별시 성동구 한림말길 11,/ 옥정중학교 (옥수동),02-6021-2100,...,서울특별시성동광진교육지원청,성동구,중,유,유,무,무,시설없음,시설없음,시설없음
4,중학교,공립,7134137,양진중학교,Yangjin Middle School,서울특별시성동광진교육지원청,4982,서울특별시 광진구 워커힐로 32,/ 양진중학교,02-2049-1200,...,서울특별시성동광진교육지원청,광진구,중,유,시설없음,유,시설없음,시설없음,시설없음,시설없음

In [16]:
# 중학교 개수 세기
num_mid_final = df_final[df_final['학교명'].isin(df_mid['학교명'])]['학교명'].nunique()
print(f'최종 데이터에서 중학교 개수: {num_mid_final}')
# 중학교 중에서도 사립과 공립 개수 세기
num_mid_public_final = df_final[(df_final['학교명'].isin(df_mid[df_mid['설립구분'] == '공립']['학교명']))]['학교명'].nunique()
num_mid_private_final = df_final[(df_final['학교명'].isin(df_mid[df_mid['설립구분'] == '사립']['학교명']))]['학교명'].nunique()
print(f'최종 데이터에서 중학교 공립 개수: {num_mid_public_final}')
print(f'최종 데이터에서 중학교 사립 개수: {num_mid_private_final}')
# 고등학교 개수 세기
num_high_final = df_final[df_final['학교명'].isin(df_high['학교명'])]['학교명'].nunique()
print(f'최종 데이터에서 고등학교 개수: {num_high_final}')
# 고등학교 중에서도 사립과 공립 개수 세기
num_high_public_final = df_final[(df_final['학교명'].isin(df_high[df_high['설립구분'] == '공립']['학교명']))]['학교명'].nunique()
num_high_private_final = df_final[(df_final['학교명'].isin(df_high[df_high['설립구분'] == '사립']['학교명']))]['학교명'].nunique()
print(f'최종 데이터에서 고등학교 공립 개수: {num_high_public_final}')
print(f'최종 데이터에서 고등학교 사립 개수: {num_high_private_final}')

최종 데이터에서 중학교 개수: 279
최종 데이터에서 중학교 공립 개수: 279
최종 데이터에서 중학교 사립 개수: 0
최종 데이터에서 고등학교 개수: 115
최종 데이터에서 고등학교 공립 개수: 115
최종 데이터에서 고등학교 사립 개수: 0

In [18]:
# 운동장 개방여부=유인 학교 개수 세기
num_open = df_final[df_final['운동장 개방여부'] == '유']['학교명'].nunique()

In [19]:
# 출력
print(f'최종 데이터에서 운동장 개방여부가 유인 학교 개수: {num_open}')

최종 데이터에서 운동장 개방여부가 유인 학교 개수: 180

In [20]:
# 이 중 중학교 개수 세기
num_open_mid = df_final[(df_final['운동장 개방여부'] == '유') & (df_final['학교명'].isin(df_mid['학교명']))]['학교명'].nunique()
# 이 중 고등학교 개수 세기
num_open_high = df_final[(df_final['운동장 개방여부'] == '유') & (df_final['학교명'].isin(df_high['학교명']))]['학교명'].nunique()
# 출력
print(f'최종 데이터에서 운동장 개방여부가 유인 중학교 개수: {num_open_mid}')
print(f'최종 데이터에서 운동장 개방여부가 유인 고등학교 개수: {num_open_high}')

최종 데이터에서 운동장 개방여부가 유인 중학교 개수: 135
최종 데이터에서 운동장 개방여부가 유인 고등학교 개수: 45